### ISSUE TITLE
Inserting citations via autocomplete inserts two @ characters

### ISSUE THREAD

**Issue by merlinthered** [renerocksai/sublime_zk#36]
When I insert a new citation by pressing the autocomplete keys (alt+/ on my Linux machine), and select one of the citations, the result is a citation with a double @ at the start. As you can see below, I did not enter any additional @ characters before.

![citation_insert](https://user-images.githubusercontent.com/2165185/35724920-b691986a-07ff-11e8-9b32-ec55570d380b.gif)

**Comment by renerocksai** [comment]
Thanks for sharing that. I noticed that too; probably was introduced as a side-effect when adding the multimarkdown style citations. This shouldn't take long to fix....

**Comment by achamess** [comment]
I also get the same problem.

**Comment by renerocksai** [comment]
it's fixed 😄 for both MMD and pandoc style citations.

**Comment by achamess** [comment]
Thanks!

As an aside, future feature – do a search in your bib file for title or something, the way you do with your ZK notes with `[[`

**Comment by achamess** [comment]
I updated the package and tried the new insert citation. When I do the key bind, nothing happens. It used to work, albeit with the `@@` problem.

**Comment by renerocksai** [comment]
This is odd. It "works for me"...
Can you try 2 things pls:

1. bring up the "view -> show console"
2. try the command "zk: Insert Citation"
3. try [@ or [# 
and see if there is an error in the console.

Or maybe your keybindings are off?
I added the following two lines into the keymap:
`
    { "keys": ["[", "@"], "command": "zk_insert_citation"},
    { "keys": ["[", "#"], "command": "zk_insert_citation"},
`

**Comment by achamess** [comment]
From the console

`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 722, in is_visible_
    ret = self.is_visible()
TypeError: is_visible() missing 1 required positional argument: 'paths'
reloading settings Packages/User/Package Control.sublime-settings
Using global /Users/alex/Dropbox/Papers3_Citations/Bibliography-Master.bib
Using global /Users/alex/Dropbox/Papers3_Citations/Bibliography-Master.bib
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "/Users/alex/Library/Application Support/Sublime Text 3/Packages/sublime_zk/sublime_zk.py", line 1417, in run
    entries = Autobib.extract_all_entries(bibfile)
  File "/Users/alex/Library/Application Support/Sublime Text 3/Packages/sublime_zk/sublime_zk.py", line 385, in extract_all_entries
    authors = Autobib.parse_authors(authors)
  File "/Users/alex/Library/Application Support/Sublime Text 3/Packages/sublime_zk/sublime_zk.py", line 411, in parse_authors
    last, first = [x.strip() for x in author.split(',')]
ValueError: too many values to unpack (expected 2)
`

Too big of a bibliography? It's ~7500 citations.

**Comment by renerocksai** [comment]
@achamess regarding search in bibfile: this is fixed in #35 
check it out 😄

**Comment by renerocksai** [comment]
@achamess  wow! what a big bibfile. 
maybe your bibfile contains an authors field with no `,` to separate first and last name. that's my fault. I think I can fix it, if that's the case

**Comment by renerocksai** [comment]
no, it's an author with more than 1 comma in its name. I have just pushed a fix. try now pls

**Comment by achamess** [comment]
`Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "/Users/alex/Library/Application Support/Sublime Text 3/Packages/sublime_zk/sublime_zk.py", line 1417, in run
    entries = Autobib.extract_all_entries(bibfile)
  File "/Users/alex/Library/Application Support/Sublime Text 3/Packages/sublime_zk/sublime_zk.py", line 385, in extract_all_entries
    authors = Autobib.parse_authors(authors)
  File "/Users/alex/Library/Application Support/Sublime Text 3/Packages/sublime_zk/sublime_zk.py", line 411, in parse_authors
    last, first = [x.strip() for x in author.split(',')]
ValueError: too many values to unpack (expected 2)
Using global /Users/alex/Dropbox/Papers3_Citations/Bibliography-Master.bib
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "/Users/alex/Library/Application Support/Sublime Text 3/Packages/sublime_zk/sublime_zk.py", line 1417, in run
    entries = Autobib.extract_all_entries(bibfile)
  File "/Users/alex/Library/Application Support/Sublime Text 3/Packages/sublime_zk/sublime_zk.py", line 385, in extract_all_entries
    authors = Autobib.parse_authors(authors)
  File "/Users/alex/Library/Application Support/Sublime Text 3/Packages/sublime_zk/sublime_zk.py", line 411, in parse_authors
    last, first = [x.strip() for x in author.split(',')]
ValueError: too many values to unpack (expected 2)
`

If this is idiosyncratic to my library, don't waste too much time on this. I'm grateful for your help already.

**Comment by renerocksai** [comment]
this is the same error using the same code:

```
last, first = [x.strip() for x in author.split(',')]
```
has been changed to
```
last, first = [x.strip() for x in author.split(',')][2]
```

maybe github needs a while? or did you not update?

we will get this to work
