### ISSUE TITLE
Advanced tag search note working

### ISSUE THREAD

**Issue by achamess** [renerocksai/sublime_zk#83]
I'm trying to use the advanced tag search. I put the tags in and get this response:

```
FuzzyFilePath cached 74 files in /Users/alex/Dropbox/Sublime_Zettel
cmd: ag --nocolor --ackmate --nonumbers -o --silent -G .*\.md (?<=\s|^)(?<!`)(\#+([^\#\s.,\/!$%\^&\*;{}\[\]'\"=`~()<>”\\]|:[a-zA-Z0-9])+) /Users/alex/Dropbox/Sublime_Zettel
Traceback (most recent call last):
  File "/Users/alex/Library/Application Support/Sublime Text 3/Packages/sublime_zk/sublime_zk.py", line 2041, in on_done
    self.extension)
  File "/Users/alex/Library/Application Support/Sublime Text 3/Packages/sublime_zk/sublime_zk.py", line 241, in advanced_tag_search
    note_tag_map = find_all_notes_all_tags_in(folder, extension)
  File "/Users/alex/Library/Application Support/Sublime Text 3/Packages/sublime_zk/sublime_zk.py", line 1150, in find_all_notes_all_tags_in
    return ExternalSearch.notes_and_tags_in(folder, extension)
  File "/Users/alex/Library/Application Support/Sublime Text 3/Packages/sublime_zk/sublime_zk.py", line 701, in notes_and_tags_in
    positions, txt_line = line.split(':', 1)
ValueError: need more than 1 value to unpack
```

**Comment by achamess** [comment]
Hey @renerocksai Any thoughts on what the error is? I know you're busy. This is just such a useful feature.
