### ISSUE TITLE
Feature request: Full-text searches

### ISSUE THREAD

**Issue by achamess** [renerocksai/sublime_zk#85]
I love this package, but I'm still finding it difficult to access my notes in the ways I want to. I like how The Archie has an omni-search bar that searches within notes and not just in the title. The Ag driven search looks at titles of notes, but not their internal contents. It'd be nice to pull up notes based on what is inside them. Do you think this is possible? My current hack is to index my ZK from Devonthink and use its very powerful search features. @renerocksai

**Comment by renerocksai** [comment]
hi, thx for your suggestions, but I'm wondering: isn't full-text-search one
of SublimeText's strengths?

or is sublimetexts's search result window not useful enough?

I'd be interested in your thoughts on that.

best,
rene

**Comment by achamess** [comment]
Hey @renerocksai 
Thanks for the reply.

Well the full-text search is regex right? Can I do complex boolean searches like "term 1" AND "term 2" AND NOT "term 3"? Also, I like how your tag searches pulls up an ordered list of notes. It would be nice to do that with full-text searches and not just tag searches. 

Basically, could one do what your advanced tag search function does but with full text search?

**Comment by achamess** [comment]
Also, speaking of. My advanced tag search continues to not work, despite updating to the most recent version. Sorry for the trouble. 

```
FuzzyFilePath cached 76 files in /Users/alex/Dropbox/Sublime_Zettel
EVENT None
cmd: ag --nocolor -l --ackmate --silent -G .*\.md #overview_2 /Users/alex/Dropbox/Sublime_Zettel
EVENT None
cmd: ag --nocolor -l --ackmate --silent -G .*\.md #overview_2 /Users/alex/Dropbox/Sublime_Zettel
reloading /Users/alex/Dropbox/Sublime_Zettel/.search_results.zkr
EVENT None
cmd: ag --nocolor --ackmate --nonumbers -o --silent -G .*\.md (?<=\s|^)(?<!`)(\#+([^\#\s.,\/!$%\^&\*;{}\[\]'\"=`~()<>”\\]|:[a-zA-Z0-9])+) /Users/alex/Dropbox/Sublime_Zettel
Traceback (most recent call last):
  File "/Users/alex/Library/Application Support/Sublime Text 3/Packages/sublime_zk/sublime_zk.py", line 2041, in on_done
    self.extension)
  File "/Users/alex/Library/Application Support/Sublime Text 3/Packages/sublime_zk/sublime_zk.py", line 241, in advanced_tag_search
    note_tag_map = find_all_notes_all_tags_in(folder, extension)
  File "/Users/alex/Library/Application Support/Sublime Text 3/Packages/sublime_zk/sublime_zk.py", line 1150, in find_all_notes_all_tags_in
    return ExternalSearch.notes_and_tags_in(folder, extension)
  File "/Users/alex/Library/Application Support/Sublime Text 3/Packages/sublime_zk/sublime_zk.py", line 701, in notes_and_tags_in
    positions, txt_line = line.split(':', 1)
ValueError: need more than 1 value to unpack

```
